spring:
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5432/encurtalink
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

info: ============== develop ==============

