spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

info: ============== production ==============